import { test, expect } from '@playwright/test';
import { PDFDocument } from 'pdf-lib';
import fs from 'node:fs';
import path from 'node:path';

const routes = ['image/compress/', 'image/resize/', 'image/convert/', 'pdf/merge/', 'pdf/extract/', 'data/csv-viewer/', 'developer/json-formatter/'];
const base = '/localtools/';
async function imageBuffer(page: import('@playwright/test').Page, width = 120, height = 60) {
  const bytes = await page.evaluate(async ({ width, height }) => { const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const c = canvas.getContext('2d')!; c.fillStyle = '#176b5b'; c.fillRect(0, 0, width, height); const blob = await new Promise<Blob>((resolve) => canvas.toBlob((value) => resolve(value!), 'image/png')); return Array.from(new Uint8Array(await blob.arrayBuffer())); }, { width, height });
  return Buffer.from(bytes);
}
async function pdfBuffer(pages: number, offset = 0) { const doc = await PDFDocument.create(); for (let i = 0; i < pages; i++) { const page = doc.addPage([300 + offset + i, 400 + i]); page.drawText(`page-${offset + i}`); } return Buffer.from(await doc.save()); }
function qa(page: import('@playwright/test').Page, name: string) { return page.screenshot({ path: path.join('artifacts/qa', `${name}.png`), fullPage: true }); }

test.beforeAll(() => fs.mkdirSync('artifacts/qa', { recursive: true }));

test('home catalogue, popular tools, search, privacy, and no console errors', async ({ page }) => {
  const errors: string[] = []; page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto(base); await expect(page.locator('.tool-card')).toHaveCount(7); await expect(page.getByText('Popular tools')).toBeVisible();
  for (const name of ['Compress Image', 'Merge PDF', 'CSV Viewer', 'JSON Formatter']) await expect(page.getByText(name, { exact: true }).first()).toBeVisible();
  await expect(page.getByText(/runtime upload/)).toBeVisible(); await page.getByPlaceholder('Try “reduce picture size”').fill('reduce picture size'); await expect(page.getByText('Compress Image', { exact: true }).first()).toBeVisible(); await qa(page, 'homepage-desktop'); expect(errors).toEqual([]);
});

test('all direct routes reload and unknown route is 404', async ({ page, request }) => { for (const route of routes) { await page.goto(`${base}${route}`); await expect(page.locator('h1')).toBeVisible(); await page.reload(); await expect(page.locator('h1')).toBeVisible(); } expect((await request.get(`${base}not-a-route/`)).status()).toBe(404); });

test('image compress, resize, convert, download, stats, and codec controls', async ({ page }) => {
  await page.goto(`${base}image/compress/`); const png = await imageBuffer(page); await page.locator('input[type=file]').setInputFiles({ name: 'fixture.png', mimeType: 'image/png', buffer: png }); await expect(page.locator('img.preview')).toBeVisible(); await page.getByRole('button', { name: 'Process image' }).click(); await expect(page.getByText(/Saved|Larger by/)).toBeVisible(); const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download' }).click(); const item = await download; expect((await item.createReadStream())!).toBeTruthy(); await qa(page, 'image-result');
  await page.goto(`${base}image/resize/`); await page.locator('input[type=file]').setInputFiles({ name: 'fixture.png', mimeType: 'image/png', buffer: png }); await page.locator('label').filter({ hasText: 'Width' }).locator('input').fill('60'); await expect(page.locator('label').filter({ hasText: 'Height' }).locator('input')).toHaveValue('30'); await page.getByRole('button', { name: 'Process image' }).click();
  await page.goto(`${base}image/convert/`); await page.locator('input[type=file]').setInputFiles({ name: 'fixture.png', mimeType: 'image/png', buffer: png }); const format = page.locator('select').first(); await format.selectOption('image/png'); await expect(page.getByText(/PNG output is lossless/)).toBeVisible(); await expect(page.getByText('Quality', { exact: true })).toBeHidden(); await page.getByRole('button', { name: 'Process image' }).click();
});

test('PDF merge and extract validate page order and friendly errors', async ({ page }) => {
  await page.goto(`${base}pdf/merge/`); await page.locator('input[type=file]').setInputFiles([{ name: 'a.pdf', mimeType: 'application/pdf', buffer: await pdfBuffer(1, 1) }, { name: 'b.pdf', mimeType: 'application/pdf', buffer: await pdfBuffer(2, 2) }, { name: 'c.pdf', mimeType: 'application/pdf', buffer: await pdfBuffer(1, 3) }]); await expect(page.getByText(/1 page/).first()).toBeVisible(); await page.getByRole('button', { name: 'Remove' }).nth(1).click(); await page.getByRole('button', { name: 'Merge PDFs' }).click(); await expect(page.getByText(/pages ready/)).toBeVisible(); await qa(page, 'pdf-selected');
  await page.goto(`${base}pdf/extract/`); await page.locator('input[type=file]').setInputFiles({ name: 'four.pdf', mimeType: 'application/pdf', buffer: await pdfBuffer(4) }); await page.getByPlaceholder('3,1-2').fill('3,1-2'); await page.getByRole('button', { name: 'Extract pages' }).click(); await expect(page.getByText('3 pages ready')).toBeVisible(); await page.getByPlaceholder('3,1-2').fill('999'); await page.getByRole('button', { name: 'Extract pages' }).click(); await expect(page.locator('.error')).toContainText('between 1 and 4'); await page.locator('input[type=file]').setInputFiles({ name: 'bad.pdf', mimeType: 'application/pdf', buffer: Buffer.from('not pdf') }); await expect(page.locator('.error')).toContainText('could not be opened');
});

test('CSV worker parses, searches, paginates, hides columns, and exports', async ({ page }) => { const rows = ['name,note,kind', 'Zoë,"hello, world",person', ...Array.from({ length: 150 }, (_, i) => `row-${i},value-${i},data`)].join('\n'); await page.goto(`${base}data/csv-viewer/`); await page.locator('input[type=file]').setInputFiles({ name: 'rows.csv', mimeType: 'text/csv', buffer: Buffer.from(rows) }); await expect(page.getByText(/151 rows/)).toBeVisible(); await page.getByPlaceholder('Search rows').fill('Zoë'); await expect(page.locator('tbody tr')).toHaveCount(1); await page.getByPlaceholder('Search rows').fill(''); await page.getByRole('button', { name: 'Next' }).click(); await expect(page.locator('tbody tr')).toHaveCount(51); await page.getByText('Show / hide columns').click(); await page.locator('.checkbox-panel input').nth(1).uncheck(); await page.getByRole('button', { name: 'Export filtered rows' }).click(); await qa(page, 'csv-populated'); });

test('JSON pretty, minify, validate, file load, clear, and download', async ({ page }) => { await page.goto(`${base}developer/json-formatter/`); const input = page.locator('textarea'); await input.fill('{"a":1}'); await page.getByRole('button', { name: 'Pretty-print' }).click(); await expect(input).toHaveValue('{\n  "a": 1\n}'); await page.getByRole('button', { name: 'Validate' }).click(); await expect(page.getByText('Valid JSON.')).toBeVisible(); await input.fill('{bad'); await page.getByRole('button', { name: 'Validate' }).click(); await expect(page.locator('.error')).toContainText('line'); await input.fill('{"b":2}'); await page.getByRole('button', { name: 'Minify' }).click(); await expect(input).toHaveValue('{"b":2}'); await qa(page, 'json-populated'); });

test('mobile layout and primary controls remain usable', async ({ page }) => { await page.goto(base, { waitUntil: 'domcontentloaded', timeout: 10000 }); await page.setViewportSize({ width: 390, height: 844 }); for (const route of routes) { await page.goto(`${base}${route}`, { waitUntil: 'domcontentloaded', timeout: 10000 }); await expect(page.locator('h1')).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); expect(await page.locator('button').first().evaluate((node) => node.getBoundingClientRect().height >= 44).catch(() => true)).toBeTruthy(); } await page.goto(`${base}data/csv-viewer/`); await expect(page.locator('input').first()).toHaveCSS('font-size', '16px'); });


test('offline shell serves every route after priming', async ({ page, context }) => { await page.goto(base); await page.evaluate(async () => { const registration = await navigator.serviceWorker.ready; if (!navigator.serviceWorker.controller) { await new Promise<void>((resolve) => navigator.serviceWorker.addEventListener('controllerchange', () => resolve(), { once: true })); } return registration.scope; }); await page.reload(); await context.setOffline(true); try { for (const route of ['', ...routes]) { await page.goto(`${base}${route}`, { waitUntil: 'domcontentloaded', timeout: 15000 }); await expect(page.locator('h1')).toBeVisible(); } } finally { await context.setOffline(false); } });


test('CSV 100k stress remains responsive', async ({ page }, testInfo) => { const csv = `id,value\n${Array.from({ length: 100000 }, (_, i) => `${i},value-${i}`).join('\n')}`; const started = Date.now(); await page.goto(`${base}data/csv-viewer/`); await page.locator('input[type=file]').setInputFiles({ name: 'stress.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) }); await expect(page.getByText(/100000 rows/)).toBeVisible({ timeout: 30000 }); const elapsed = Date.now() - started; testInfo.annotations.push({ type: 'csv-stress-ms', description: String(elapsed) }); fs.writeFileSync('/tmp/localtools-csv-stress-ms.txt', String(elapsed)); await page.getByPlaceholder('Search rows').fill('value-99999'); await expect(page.locator('tbody tr')).toHaveCount(1); });

test('processing makes no cross-origin or mutating network requests', async ({ page }) => { await page.goto(`${base}image/compress/`); const requests: { url: string; method: () => string }[] = []; page.on('request', (request) => requests.push({ url: request.url(), method: () => request.method() })); await page.locator('input[type=file]').setInputFiles({ name: 'network.png', mimeType: 'image/png', buffer: await imageBuffer(page) }); await page.getByRole('button', { name: 'Process image' }).click(); await expect(page.getByText(/Saved|Larger by/)).toBeVisible(); const bad = requests.filter((request) => new URL(request.url).origin !== new URL(page.url()).origin); const mutating = requests.filter((request) => ['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method())); fs.writeFileSync('/tmp/localtools-network-gets.txt', requests.filter((request) => request.method() === 'GET').map((request) => new URL(request.url).pathname).join('\n')); expect(bad).toEqual([]); expect(mutating).toEqual([]); });
