import { SAFETY } from './safety';
import { csvToText, download, filterCsvRows, sortCsvRows } from './utils';
import { button, dropzone, el, privacy, seo, setError } from './ui';
import type { Tool } from './registry';
type CsvResponse = { type: 'state'; state: 'processing' | 'parsed' } | { type: 'done'; rows: string[][] } | { type: 'error'; message: string };
export function renderCsvTool(tool: Tool, finish: (main: HTMLElement, title: string) => void) {
  const main = el('main', 'tool-page'); const panel = el('section', 'panel'); panel.append(el('div', 'eyebrow', tool.category), el('h1', undefined, tool.name), el('p', 'lede', tool.description)); panel.insertAdjacentHTML('beforeend', privacy); const dz = dropzone('.csv,text/csv,text/plain'); panel.append(dz.wrap);
  const status = el('div', 'csv-status', 'Idle — choose a CSV file.'); status.setAttribute('aria-live', 'polite'); panel.append(status); const error = el('div', 'error hidden'); panel.append(error); const meta = el('div', 'csv-meta'); const summary = el('span'); const search = el('input') as HTMLInputElement; search.placeholder = 'Search rows'; const col = el('select') as HTMLSelectElement; const value = el('input') as HTMLInputElement; value.placeholder = 'Column filter'; meta.append(summary, search, col, value); panel.append(meta); const details = el('details'); details.append(el('summary', undefined, 'Show / hide columns')); const checks = el('div', 'checkbox-panel'); details.append(checks); panel.append(details); const tableWrap = el('div', 'table-wrap'); panel.append(tableWrap); const pager = el('div', 'button-row'); const prev = button('Previous'); const next = button('Next'); pager.append(prev, next); panel.append(pager); const exportButton = button('Export filtered rows', 'primary'); exportButton.disabled = true; panel.append(exportButton);
  let headers: string[] = []; let rows: string[][] = []; let filtered: string[][] = []; let page = 0; const hidden = new Set<number>(); const render = () => { filtered = filterCsvRows(rows, search.value, col.value === '' ? null : Number(col.value), value.value); const pageRows = filtered.slice(page * SAFETY.csvPageSize, (page + 1) * SAFETY.csvPageSize); summary.textContent = `${rows.length} rows · ${headers.length} columns · ${filtered.length} shown`; prev.disabled = page === 0; next.disabled = (page + 1) * SAFETY.csvPageSize >= filtered.length; const table = document.createElement('table'); const thead = document.createElement('thead'); const tr = document.createElement('tr'); headers.forEach((header, index) => { if (hidden.has(index)) return; const th = document.createElement('th'); const sort = button(header || `Column ${index + 1}`, 'sort'); sort.onclick = () => { rows = sortCsvRows(rows, index, 1); render(); }; th.append(sort); tr.append(th); }); thead.append(tr); table.append(thead); const tbody = document.createElement('tbody'); pageRows.forEach((row) => { const rowElement = document.createElement('tr'); row.forEach((cell, index) => { if (!hidden.has(index)) rowElement.append(el('td', undefined, cell)); }); tbody.append(rowElement); }); table.append(tbody); tableWrap.replaceChildren(table); };
  let worker: Worker | null = null; let requestId = 0;
  dz.input.onchange = async () => { const file = dz.input.files?.[0]; if (!file) return; const current = ++requestId; worker?.terminate(); worker = null; status.textContent = 'Loading CSV…'; setError(error); exportButton.disabled = true; try { if (file.size > SAFETY.maxCsvBytes) throw Error('CSV files must be smaller than 50.0 MB.'); const text = await file.text(); if (current !== requestId) return; status.textContent = 'Processing CSV…'; worker = new Worker(new URL('./workers/csv.worker.ts', import.meta.url), { type: 'module' }); worker.onmessage = (event: MessageEvent<CsvResponse>) => { if (current !== requestId) return; const message = event.data; if (message.type === 'state') status.textContent = message.state === 'parsed' ? 'Finalizing CSV…' : 'Processing CSV…'; else if (message.type === 'done') { const parsed = message.rows; if (parsed.length > SAFETY.maxCsvRows) { status.textContent = 'CSV error.'; setError(error, 'This CSV exceeds the safe 250,000-row limit.'); return; } rows = parsed.slice(1); headers = parsed[0] || []; const max = rows.reduce((count, row) => Math.max(count, row.length), headers.length); headers = headers.concat(Array.from({ length: max - headers.length }, (_, i) => `Column ${headers.length + i + 1}`)); col.replaceChildren(new Option('All columns', '')); headers.forEach((header, i) => col.add(new Option(header || `Column ${i + 1}`, String(i)))); checks.replaceChildren(...headers.map((header, i) => { const label = el('label', 'check'); const checkbox = el('input') as HTMLInputElement; checkbox.type = 'checkbox'; checkbox.checked = true; checkbox.onchange = () => { checkbox.checked ? hidden.delete(i) : hidden.add(i); render(); }; label.append(checkbox, document.createTextNode(` ${header || `Column ${i + 1}`}`)); return label; })); exportButton.disabled = false; status.textContent = 'CSV ready.'; render(); } else { status.textContent = 'CSV error.'; setError(error, 'Could not parse this CSV. Check its quotes and rows.'); } }; worker.postMessage({ type: 'parse', text }); } catch (e) { status.textContent = 'CSV error.'; setError(error, e instanceof Error ? e.message : 'Could not read this CSV.'); } };
  [search, value, col].forEach((node) => node.addEventListener('input', () => { page = 0; render(); })); next.onclick = () => { page += 1; render(); }; prev.onclick = () => { page -= 1; render(); }; exportButton.onclick = () => download(new Blob([csvToText(headers.filter((_, i) => !hidden.has(i)), filtered.map((row) => row.filter((_, i) => !hidden.has(i))))], { type: 'text/csv' }), 'localtools-filtered.csv'); panel.insertAdjacentHTML('beforeend', seo(tool)); main.append(panel); finish(main, tool.name);
}
