import { decodeImage, extFor, lockedHeight, lockedWidth, renderImage, supportedImageTypes, usesLossyQuality, validateDimensions } from './image';
import { SAFETY, formatBytes, validateFiles } from './safety';
import { button, dropzone, el, privacy, seo, setError } from './ui';
import type { Tool } from './registry';
import { download } from './utils';

export function renderImageTool(tool: Tool, finish: (main: HTMLElement, title: string) => void, clearUrls: () => void, rememberUrl: (url: string) => string) {
  const main = el('main', 'tool-page'); const panel = el('section', 'panel');
  panel.append(el('div', 'eyebrow', tool.category), el('h1', undefined, tool.name), el('p', 'lede', tool.description)); panel.insertAdjacentHTML('beforeend', privacy);
  const dz = dropzone(tool.accepted.join(',')); panel.append(dz.wrap);
  const previewRow = el('div', 'preview-row hidden'); const preview = el('img', 'preview') as HTMLImageElement; preview.alt = 'Selected image preview'; const info = el('span'); previewRow.append(preview, info); panel.append(previewRow);
  const controls = el('div', 'controls'); const formatLabel = el('label', undefined, 'Output format'); const format = el('select') as HTMLSelectElement;
  supportedImageTypes().forEach((type) => format.add(new Option(type.split('/')[1].toUpperCase(), type))); formatLabel.append(format); controls.append(formatLabel);
  const width = el('input') as HTMLInputElement; width.type = 'number'; width.min = '1'; width.max = '12000'; const height = el('input') as HTMLInputElement; height.type = 'number'; height.min = '1'; height.max = '12000';
  const widthLabel = el('label', undefined, 'Width (px)'); widthLabel.append(width); const heightLabel = el('label', undefined, 'Height (px)'); heightLabel.append(height);
  const lockLabel = el('label', 'check'); const lock = el('input') as HTMLInputElement; lock.type = 'checkbox'; lock.checked = true; lockLabel.append(lock, document.createTextNode(' Lock aspect ratio'));
  if (tool.id !== 'convert-image') controls.append(widthLabel, heightLabel, lockLabel);
  const presetLabel = el('label', undefined, 'Resize preset'); const preset = el('select') as HTMLSelectElement;
  preset.append(new Option('Choose a preset', ''), new Option('50%', '0.5'), new Option('75%', '0.75'), new Option('Original', '1')); presetLabel.append(preset); if (tool.id === 'resize-image') controls.append(presetLabel);
  const qualityLabel = el('label', undefined, 'Quality'); const quality = el('input') as HTMLInputElement; quality.type = 'range'; quality.min = '1'; quality.max = '100'; quality.value = '82'; const qualityNote = el('small', undefined, '82'); qualityLabel.append(quality, qualityNote); controls.append(qualityLabel); panel.append(controls);
  const note = el('p', 'lede'); panel.append(note); const actions = el('div', 'button-row'); const process = button('Process image', 'primary'); const reset = button('Reset'); process.disabled = true; actions.append(process, reset); panel.append(actions);
  const error = el('div', 'error hidden'); panel.append(error); const result = el('div', 'result hidden'); panel.append(result); let file: File | null = null; let original = { width: 0, height: 0 }; let output: Blob | null = null;
  const updateQuality = () => { const lossy = usesLossyQuality(format.value); qualityLabel.classList.toggle('hidden', !lossy); note.textContent = format.value === 'image/png' ? 'PNG output is lossless; quality control is disabled.' : ''; }; format.addEventListener('change', updateQuality); updateQuality();
  preset.addEventListener('change', () => { if (!original.width || !preset.value) return; const scale = Number(preset.value); width.value = String(Math.round(original.width * scale)); height.value = String(Math.round(original.height * scale)); });
  dz.input.addEventListener('change', async () => { clearUrls(); file = dz.input.files?.[0] || null; result.classList.add('hidden'); if (!file) return; try { validateFiles([file], tool.accepted, SAFETY.maxFileBytes); const image = await decodeImage(file); original = { width: image.naturalWidth, height: image.naturalHeight }; width.value = String(original.width); height.value = String(original.height); preview.src = rememberUrl(URL.createObjectURL(file)); previewRow.classList.remove('hidden'); info.textContent = `${file.name} · ${formatBytes(file.size)} · ${original.width}×${original.height}`; process.disabled = false; setError(error); } catch (e) { setError(error, e instanceof Error ? e.message : 'Could not read this image.'); process.disabled = true; } });
  width.addEventListener('input', () => { if (lock.checked && original.width) height.value = String(lockedHeight(Number(width.value), original.width, original.height)); }); height.addEventListener('input', () => { if (lock.checked && original.height) width.value = String(lockedWidth(Number(height.value), original.width, original.height)); });
  process.addEventListener('click', async () => { if (!file) return; process.disabled = true; process.textContent = 'Processing…'; try { const w = tool.id === 'convert-image' ? original.width : Number(width.value); const h = tool.id === 'convert-image' ? original.height : Number(height.value); validateDimensions(w, h); output = await renderImage(file, w, h, format.value, Number(quality.value) / 100); const percent = (file.size - output.size) / file.size * 100; result.replaceChildren(el('strong', undefined, `${formatBytes(file.size)} → ${formatBytes(output.size)}`), el('span', undefined, percent >= 0 ? `Saved ${formatBytes(file.size - output.size)} (${percent.toFixed(1)}%)` : `Larger by ${formatBytes(output.size - file.size)}`)); const save = button('Download', 'primary'); save.addEventListener('click', () => download(output!, `${file!.name.replace(/\.[^.]+$/, '')}.${extFor(format.value)}`)); result.append(save); result.classList.remove('hidden'); setError(error); } catch (e) { setError(error, e instanceof Error ? e.message : 'Could not process this image.'); } finally { process.disabled = false; process.textContent = 'Process image'; } });
  reset.addEventListener('click', () => { clearUrls(); file = null; output = null; dz.input.value = ''; preview.removeAttribute('src'); previewRow.classList.add('hidden'); result.classList.add('hidden'); process.disabled = true; });
  panel.insertAdjacentHTML('beforeend', seo(tool)); main.append(panel); finish(main, tool.name);
}
