import { TOOLS, routeFor, searchTools, toolForPath, type Tool, type ToolModule } from './registry';
import { renderImageTool } from './image-module';
import { renderPdfTool } from './pdf-module';
import { renderCsvTool } from './csv-module';
import { renderJsonTool } from './json-module';
import { renderMetadataCleaner } from './metadata-module';
import { button, el } from './ui';
import './styles.css';
const base = document.querySelector('base')?.getAttribute('href') || (import.meta.env.BASE_URL || '/'); const app = document.querySelector<HTMLDivElement>('#app')!; const homeRoute = base === '/' ? '/' : base; let objectUrls: string[] = [];
const rememberUrl = (url: string) => { objectUrls.push(url); return url; }; function clearUrls() { objectUrls.forEach((url) => URL.revokeObjectURL(url)); objectUrls = []; } window.addEventListener('pagehide', clearUrls);
function header() { const top = el('header', 'top'); const brand = el('a', 'brand'); brand.href = homeRoute; brand.innerHTML = '<span class="brand-mark">✦</span>LocalTools'; top.append(brand); const nav = el('nav'); const link = el('a', undefined, 'All tools'); link.href = homeRoute; nav.append(link); top.append(nav); return top; }
function shell(content: HTMLElement, title: string) { document.title = `${title} — LocalTools`; app.replaceChildren(header(), content); registerPwa(); }
function home() { const main = el('main', 'home'); const hero = el('section', 'hero'); hero.append(el('div', 'eyebrow', 'Private by design'), el('h1', undefined, 'Useful tools. Quietly local.'), el('p', 'lede', 'Private tools that run entirely in your browser.'), el('p', 'privacy-promise', 'No uploads. No accounts. Your files stay on your device.')); const searchWrap = el('div', 'search-wrap'); const label = el('label', undefined, 'Find a tool'); const search = el('input') as HTMLInputElement; search.type = 'search'; search.placeholder = 'Try “reduce picture size”'; search.setAttribute('aria-label', 'Find a tool'); const results = el('div'); searchWrap.append(label, search, results); hero.append(searchWrap); main.append(hero); const popular = el('section', 'category popular'); const popHead = el('div', 'section-head'); popHead.append(el('h2', undefined, 'Popular tools'), el('span', undefined, 'Four quick starts')); const popGrid = el('div', 'tool-grid'); popular.append(popHead, popGrid); main.append(popular); const categories = new Map<string, HTMLElement>(); for (const tool of TOOLS) { if (!categories.has(tool.category)) { const section = el('section', 'category'); section.append(el('h2', undefined, tool.category)); const grid = el('div', 'tool-grid'); section.append(grid); categories.set(tool.category, grid); main.append(section); } } const card = (tool: Tool) => { const a = el('a', 'tool-card'); a.href = routeFor(tool, base); const copy = el('span'); copy.append(el('strong', undefined, tool.name), el('small', undefined, tool.description)); a.append(el('span', 'tool-icon', tool.icon), copy, el('span', 'arrow', '→')); return a; }; const render = (found: Tool[]) => { popGrid.replaceChildren(); categories.forEach((grid) => grid.replaceChildren()); if (search.value.trim()) results.replaceChildren(...found.map(card)); else { results.replaceChildren(); popGrid.replaceChildren(...TOOLS.filter((tool) => tool.popular).map(card)); found.forEach((tool) => categories.get(tool.category)?.append(card(tool))); } }; search.oninput = () => render(searchTools(search.value)); render(TOOLS); const privacy = el('section', 'privacy-card'); privacy.append(el('h2', undefined, 'Your files stay yours.'), el('p', undefined, 'No account, backend, telemetry, or runtime upload. Processing happens in browser memory and the app can work offline after it is primed.')); privacy.insertAdjacentHTML('beforeend', '<p class="seo-details"><strong>What this tool does:</strong> a focused set of browser utilities for images, PDFs, CSV, and JSON. <strong>Privacy:</strong> local processing only. <strong>Supported formats:</strong> images (JPG, PNG, WebP), PDFs, CSV/UTF-8 text, and JSON. <strong>FAQ:</strong> files are not uploaded or persisted by default.</p>'); main.append(privacy, el('footer', undefined, 'LocalTools · private browser tools')); shell(main, 'Private browser tools'); }
function registerPwa() { if (!('serviceWorker' in navigator)) return; navigator.serviceWorker.register(`${base}sw.js`).then((registration) => { const show = (worker: ServiceWorker) => { const banner = el('div', 'update-banner'); banner.setAttribute('role', 'status'); banner.append(el('span', undefined, 'A new LocalTools version is ready.')); const update = button('Update now', 'primary'); let busy = false; update.onclick = () => { if (busy) return; busy = true; update.disabled = true; const overlay = el('div', 'update-state', 'Updating LocalTools…'); document.body.append(overlay); window.setTimeout(() => worker.postMessage({ type: 'SKIP_WAITING' }), 150); const timeout = window.setTimeout(() => { overlay.textContent = 'Update could not be completed. Please try again later.'; update.disabled = false; busy = false; }, 12000); navigator.serviceWorker.addEventListener('controllerchange', () => { clearTimeout(timeout); location.reload(); }, { once: true }); }; banner.append(update); document.body.append(banner); }; if (registration.waiting) show(registration.waiting); registration.addEventListener('updatefound', () => { const installing = registration.installing; installing?.addEventListener('statechange', () => { if (installing.state === 'installed' && navigator.serviceWorker.controller) show(installing); }); }); }).catch(() => undefined); }
const modules: Record<ToolModule, (tool: Tool) => void> = { image: (tool) => renderImageTool(tool, shell, clearUrls, rememberUrl), metadata: (tool) => renderMetadataCleaner(tool, shell, clearUrls, rememberUrl), pdf: (tool) => renderPdfTool(tool, shell), csv: (tool) => renderCsvTool(tool, shell), json: (tool) => renderJsonTool(tool, shell) };
function route() { clearUrls(); const tool = toolForPath(location.pathname, base); if (tool) modules[tool.module](tool); else home(); }
route();
