import { SAFETY, formatBytes, validateFiles } from './safety';
import { download, parsePageExpression } from './utils';
import { button, dropzone, el, privacy, seo, setError } from './ui';
import type { Tool } from './registry';
async function pdfLib() { return import('pdf-lib'); }
export function renderPdfTool(tool: Tool, finish: (main: HTMLElement, title: string) => void) {
  const mode = tool.id === 'merge-pdf' ? 'merge' : 'extract'; const main = el('main', 'tool-page'); const panel = el('section', 'panel'); panel.append(el('div', 'eyebrow', tool.category), el('h1', undefined, tool.name), el('p', 'lede', tool.description)); panel.insertAdjacentHTML('beforeend', privacy); const dz = dropzone('application/pdf,.pdf', mode === 'merge'); panel.append(dz.wrap); const list = el('div', 'file-list'); panel.append(list); const controls = el('div', 'controls'); let expression: HTMLInputElement | undefined;
  if (mode === 'extract') { const label = el('label', undefined, 'Pages to extract'); expression = el('input') as HTMLInputElement; expression.placeholder = '3,1-2'; label.append(expression); controls.append(label); } panel.append(controls); const run = button(mode === 'merge' ? 'Merge PDFs' : 'Extract pages', 'primary'); run.disabled = true; panel.append(el('div', 'button-row')); panel.lastElementChild!.append(run); const error = el('div', 'error hidden'); panel.append(error); const result = el('div', 'result hidden'); panel.append(result); let files: { file: File; pages: number }[] = [];
  const renderList = () => { list.replaceChildren(); files.forEach((entry, index) => { const row = el('div', 'file-row'); row.append(el('span', undefined, `${entry.file.name} · ${formatBytes(entry.file.size)} · ${entry.pages} page${entry.pages === 1 ? '' : 's'}`)); const up = button('Up', 'remove'); const down = button('Down', 'remove'); const remove = button('Remove', 'remove'); up.disabled = index === 0; down.disabled = index === files.length - 1; up.onclick = () => { [files[index - 1], files[index]] = [files[index], files[index - 1]]; renderList(); }; down.onclick = () => { [files[index + 1], files[index]] = [files[index], files[index + 1]]; renderList(); }; remove.onclick = () => { files.splice(index, 1); renderList(); }; row.append(up, down, remove); list.append(row); }); run.disabled = !files.length; };
  dz.input.addEventListener('change', async () => { try { const incoming = Array.from(dz.input.files || []); validateFiles(incoming, ['application/pdf'], mode === 'merge' ? SAFETY.maxAggregateBytes : SAFETY.maxFileBytes); const { PDFDocument } = await pdfLib(); const next: { file: File; pages: number }[] = []; for (const file of incoming) next.push({ file, pages: (await PDFDocument.load(await file.arrayBuffer())).getPageCount() }); files = mode === 'merge' ? [...files, ...next] : next.slice(0, 1); setError(error); renderList(); } catch { setError(error, 'This PDF could not be opened. Check that it is a valid, unencrypted PDF.'); } });
  run.onclick = async () => { run.disabled = true; run.textContent = 'Processing…'; try { const { PDFDocument } = await pdfLib(); const out = await PDFDocument.create(); if (mode === 'merge') for (const entry of files) { const source = await PDFDocument.load(await entry.file.arrayBuffer()); (await out.copyPages(source, source.getPageIndices())).forEach((page) => out.addPage(page)); } else { const source = await PDFDocument.load(await files[0].file.arrayBuffer()); const pages = parsePageExpression(expression!.value, source.getPageCount()); (await out.copyPages(source, pages.map((page) => page - 1))).forEach((page) => out.addPage(page)); } const blob = new Blob([new Uint8Array(await out.save()) as unknown as BlobPart], { type: 'application/pdf' }); const count = out.getPageCount(); result.replaceChildren(el('strong', undefined, `${count} page${count === 1 ? '' : 's'} ready`)); const save = button(mode === 'merge' ? 'Download merged PDF' : 'Download extracted PDF', 'primary'); save.onclick = () => download(blob, mode === 'merge' ? 'localtools-merged.pdf' : 'localtools-extracted.pdf'); result.append(save); result.classList.remove('hidden'); setError(error); } catch (e) { const message = e instanceof Error && (e.message.startsWith('Pages') || e.message.startsWith('Invalid page')) ? e.message : 'Could not process this PDF. Check the file and page selection.'; setError(error, message); } finally { run.disabled = false; run.textContent = mode === 'merge' ? 'Merge PDFs' : 'Extract pages'; } }; panel.insertAdjacentHTML('beforeend', seo(tool)); main.append(panel); finish(main, tool.name);
}
