export type Category='Images'|'PDF'|'Data'|'Developer';
export type Tool={id:string;name:string;description:string;category:Category;route:string;icon:string;keywords:string[];accepted:string[];offline:true;capabilities:string[];status:'ready'};
export const TOOLS:Tool[]=[
 {id:'compress-image',name:'Compress Image',description:'Reduce picture size while keeping it looking sharp.',category:'Images',route:'/image/compress/',icon:'◌',keywords:['compress','reduce','picture','photo','size','optimize'],accepted:['image/jpeg','image/png','image/webp'],offline:true,capabilities:['JPG','PNG','WebP'],status:'ready'},
 {id:'resize-image',name:'Resize Image',description:'Change image dimensions without accidental stretching.',category:'Images',route:'/image/resize/',icon:'↗',keywords:['resize','dimensions','scale','width','height'],accepted:['image/jpeg','image/png','image/webp'],offline:true,capabilities:['Aspect lock','Presets'],status:'ready'},
 {id:'convert-image',name:'Convert Image',description:'Switch between JPG, PNG, and WebP in a click.',category:'Images',route:'/image/convert/',icon:'⇄',keywords:['convert','format','jpg','png','webp','image'],accepted:['image/jpeg','image/png','image/webp'],offline:true,capabilities:['JPG','PNG','WebP'],status:'ready'},
 {id:'merge-pdf',name:'Merge PDF',description:'Join PDFs in the order you choose.',category:'PDF',route:'/pdf/merge/',icon:'▤',keywords:['merge','join','combine','pdf'],accepted:['application/pdf'],offline:true,capabilities:['Reorder','Remove'],status:'ready'},
 {id:'extract-pdf',name:'Extract PDF Pages',description:'Save selected pages from a PDF as a new file.',category:'PDF',route:'/pdf/extract/',icon:'▥',keywords:['extract','split','pages','pdf'],accepted:['application/pdf'],offline:true,capabilities:['Page ranges','Validation'],status:'ready'},
 {id:'csv-viewer',name:'CSV Viewer',description:'Explore large CSVs with search, sort, filters, and export.',category:'Data',route:'/data/csv-viewer/',icon:'▦',keywords:['csv','spreadsheet','table','data','filter','comma'],accepted:['text/csv','text/plain'],offline:true,capabilities:['100k+ rows','Worker parsing'],status:'ready'},
 {id:'json-formatter',name:'JSON Formatter',description:'Pretty-print, minify, validate, and download JSON.',category:'Developer',route:'/developer/json-formatter/',icon:'{}',keywords:['json','format','pretty','minify','validate','developer'],accepted:['application/json','text/plain'],offline:true,capabilities:['Pretty','Minify'],status:'ready'}
];
export const toolForPath=(path:string)=>TOOLS.find(t=>path.replace(/index\.html$/,'').startsWith(t.route)) ?? null;
